# Generated by Django 3.2.6 on 2021-08-18 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rare_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rare_api.post')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rare_api.tag')),
            ],
        ),
    ]
