# Generated by Django 3.2.6 on 2021-08-17 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rare_api', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rare_api.post')),
                ('rare_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rare_api.rareuser')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rare_api.reaction')),
            ],
        ),
    ]
