# Generated by Django 3.2.6 on 2021-08-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rare_api', '0002_posttag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reactions',
            field=models.ManyToManyField(through='rare_api.PostReaction', to='rare_api.Reaction'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(through='rare_api.PostTag', to='rare_api.Tag'),
        ),
    ]
