# Generated by Django 3.2.6 on 2021-08-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rare_api', '0002_posttag'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='publication_date',
            field=models.DateField(default="2020-01-01"),
            preserve_default=False,
        ),
    ]
